#!/usr/bin/with-contenv bash
# shellcheck shell=bash

EXITCODE=0
# Define bash colours
NOCOLOR='\033[0m'
LIGHTRED='\033[1;31m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'

# Set up timezone
if [ -z "${TZ}" ]; then
  echo "${YELLOW}WARNING: TZ environment variable not set${NOCOLOR}"
else
  ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime && echo "$TZ" > /etc/timezone
fi
# BeastHost
if [ -z "${BEAST_HOST}" ]; then
  echo -e "${LIGHTRED}ERROR: BEAST_HOST environment variable not set${NOCOLOR}"
  EXITCODE=1
fi
# Handle "-e MYUSERNAME"
if [ -z "${MYUSERNAME}" ]; then
  echo -e "${LIGHTRED}ERROR: MYUSERNAME environment variable not set${NOCOLOR}"
  EXITCODE=1
fi
# Handle "-e LATITUDE"
if [ -z "${LATITUDE}" ]; then
  echo -e "${LIGHTRED}ERROR: LATITUDE environment variable not set${NOCOLOR}"
  EXITCODE=1
fi
# Handle "-e LONGITUDE"
if [ -z "${LONGITUDE}" ]; then
  echo -e "${LIGHTRED}ERROR: LONGITUDE environment variable not set${NOCOLOR}"
  EXITCODE=1
fi
# Handle "-e ALTITUDE"
if [ -z "${ALTITUDE}" ]; then
  echo -e "${LIGHTRED}ERROR: ALTITUDE environment variable not set${NOCOLOR}"
  EXITCODE=1
fi
# UUID
if [ -z "${ADSBX_UUID}" ]; then
  echo -e "${YELLOW}WARNING: ADSBX_UUID environment variable not set, new UUID will be generated${NOCOLOR}"
  UUIDGEN=$(command -v uuidgen)
  UUID=$($UUIDGEN)
  echo -e "${CYAN}WARNING: Please restart the container with environment variable ADSBX_UUID=${UUID} environment variable"
  EXITCODE=1
else
  if ! [[ "${ADSBX_UUID}" =~ ^\{?[A-F0-9a-f]{8}-[A-F0-9a-f]{4}-[A-F0-9a-f]{4}-[A-F0-9a-f]{4}-[A-F0-9a-f]{12}\}?$ ]]; then
    echo -e "${LIGHTRED}ERROR: Data in ADSBX_UUID environment variable was invalid.${NOCOLOR}"
    EXITCODE=1
  fi
fi
# All is good ?
if [ $EXITCODE == 0 ]; then
  echo -e "${CYAN}INFO: Connect to $BEAST_HOST${NOCOLOR}"
fi

exit $EXITCODE
