#!/usr/bin/with-contenv bash
# shellcheck shell=bash

EXITCODE=0

# Set up timezone
if [ -z "${TZ}" ]; then
  echo "WARNING: TZ environment variable not set"
else
  ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime && echo "$TZ" > /etc/timezone
fi
# BeastHost
if [ -z "${BEAST_HOST}" ]; then
  echo -e "ERROR: BEAST_HOST environment variable not set"
  EXITCODE=1
fi
# Handle "-e MYUSERNAME"
if [ -z "${MYUSERNAME}" ]; then
  echo -e "ERROR: MYUSERNAME environment variable not set"
  EXITCODE=1
fi
# Handle "-e LATITUDE"
if [ -z "${LATITUDE}" ]; then
  echo -e "ERROR: LATITUDE environment variable not set"
  EXITCODE=1
fi
# Handle "-e LONGITUDE"
if [ -z "${LONGITUDE}" ]; then
  echo -e "ERROR: LONGITUDE environment variable not set"
  EXITCODE=1
fi
# Handle "-e ALTITUDE"
if [ -z "${ALTITUDE}" ]; then
  echo -e "ERROR: ALTITUDE environment variable not set"
  EXITCODE=1
fi
# UUID
if [ -z "${ADSBX_UUID}" ]; then
  echo -e "WARNING: ADSBX_UUID environment variable not set, new UUID will be generated"
  UUIDGEN=$(command -v uuidgen)
  UUID=$($UUIDGEN)
  echo -e "WARNING: Please restart the container with environment variable ADSBX_UUID=${UUID} environment variable"
  EXITCODE=1
else
  if ! [[ "${ADSBX_UUID}" =~ ^\{?[A-F0-9a-f]{8}-[A-F0-9a-f]{4}-[A-F0-9a-f]{4}-[A-F0-9a-f]{4}-[A-F0-9a-f]{12}\}?$ ]]; then
    echo -e "ERROR: Data in ADSBX_UUID environment variable was invalid."
    EXITCODE=1
  fi
fi
# All is good ?
if [ $EXITCODE == 0 ]; then
  # shellcheck disable=SC2153
  echo -e "INFO: Connect to ${BEAST_HOST}:${BEAST_PORT}"
fi

exit $EXITCODE
